### ISSUE TITLE
Option to have both tap and click be active at the same time

### ISSUE THREAD

**Issue by furiousdom** [artginzburg/MiddleClick-BigSur#43] opened 2022-08-19 08:15 UTC
In the status bar when MiddleClick app is clicked, the user is presented with two options:
X Finger Click
X Finger Tap

Current behaviour: only one of these can be active at the same time

Desired behaviour: both options can be active at the same time

P.S. The visual indicator that one of the two options is a check mark, which should mean that both options can be active at the same time, but they can't.

**Comment by artginzburg** [comment] 2022-09-04 10:49
Duplicate of #17 — gonna continue there.

P.S. I suppose a check mark does not indicate that both can be active, reference: built-in keyboard layout switcher. But I see your point and it sounds logical, just've never seen the check mark this way.

**Closed** 2022-09-04 10:49 UTC
