### ISSUE TITLE
Older OS support

### ISSUE THREAD

**Issue by franzuu** [artginzburg/MiddleClick-BigSur#1] opened 2019-08-26 09:24 UTC
Hi thank you for guiding me to your fork! I tried to use it on High Sierra, but still getting this error:
You can't use this version of the application "MiddleClick.app" with this version of macOS
You have macOS 10.13.6. The application requires macOS 10.14 or later.
I used brew to install version 2.4.4
Thank you!

**Comment by DaFuqtor** [comment] 2019-10-09 19:59
If anyone is going to look into this issue, note that @franzuu uses Hackintosh.

**Comment by soraxxo** [comment] 2020-01-12 06:01
I just tried installing from brew to a macOS 10.13.6 system on official Apple hardware, and am also being told that the application (v2.4.5 as of this writing) requires macOS 10.14 at minimum. The issue is not specific to Hackintosh builds.

**Comment by soraxxo** [comment] 2020-01-12 06:17
For what it's worth - I tried the 1.0 build from the original project repo, and the application does run, but it does not seem to work for me (that version only works with tapping and I have tap-to-click turned off on my system, which I suppose is my problem, but that is beside the point).

Until the compatibility issue is resolved on this fork, anybody on High Sierra or earlier who stumbles across this post may want to try their luck with that upstream build: https://github.com/cl3m/MiddleClick/releases/tag/1.0

**Comment by gingerbeardman** [comment] 2020-02-11 23:56
Annoying that this has not changed to Catalina-Only.

**Comment by DaFuqtor** [comment] 2020-02-12 07:21
> Annoying that with 2.4.6 this has now changed to being Catalina-Only. Why?
> 
> So here's a (unsigned) build of 2.4.6 that will run on 10.13, 10.14 and 10.15. I just now built it from code on Mojave: [MiddleClick.app.zip](https://github.com/DaFuqtor/MiddleClick-Catalina/files/4189199/MiddleClick.app.zip)

I wonder if this will work with 10.9 as minimum system version

**Comment by gingerbeardman** [comment] 2020-02-12 11:29
Here it is! 2.4.6 compiled (unsigned) with minimum 10.9 and runs fine on Mojave for me.

[MiddleClick.app.zip](https://github.com/DaFuqtor/MiddleClick-Catalina/files/4191793/MiddleClick.app.zip)

**Comment by artginzburg** [comment] 2022-08-31 13:35
Closing as MiddleClick is currently built for minimum possible deployment target (10.9)

**Closed by artginzburg** 2022-08-31 13:35 UTC
Labels: bug, help wanted
