### ISSUE TITLE
The icon in Menu bar is blinking

### ISSUE THREAD

**Issue by fires3as0n** [artginzburg/MiddleClick-BigSur#38] opened 2022-01-26 03:08 UTC
The icon in menu bar disappears and then appears again every couple of seconds, I suppose this is a bug.

**Comment by c0pland** [comment] 2022-02-06 03:10
This worked for me.

1. Kill the app
2. Launch it via terminal `/Applications/MiddleClick.app/Contents/MacOS/MiddleClick`
3. It will ask for Accessibility permission, grant it. If the checkbox is already checked, uncheck and check again.
4. ???
5. PROFIT

**Comment by Karatekid2407** [comment] 2022-02-06 18:46
worked for me

**Comment by MrJer** [comment] 2022-02-27 18:57
Worked for me as well. Thanks!

**Comment by denizevrenci** [comment] 2022-03-07 16:34
Launching from the terminal stops it but if you kill the app and launch again from spotlight, it goes back to blinking again.

**Comment by urosctd** [comment] 2022-06-12 15:22
I had the same issue.. What did the trick for me, I went to `System Preferences`>`Security and Privacy`>`Privacy`>`Accessibility` unticked middle click, reinstalled it the ticked it back on in Accessibility.

**Comment by ElectricS01** [comment] 2022-08-03 13:12
That worked for me thanks urosctd

**Comment by gapnav** [comment] 2022-08-27 20:40
since today macos says that it's a malware and proposes to move it to trash, but no option to whitelist it or something 😞

**Comment by artginzburg** [comment] 2022-08-27 23:12
@gapnav this is common for open-source apps, try opening it via <kbd>Ctrl</kbd>+<kbd>Click</kbd> > `Open`

**Comment by daryllimyt** [comment] 2022-08-28 17:37
> since today macos says that it's a malware and proposes to move it to trash, but no option to whitelist it or something 😞

I have been experiencing the same thing as of today and opening via `Ctrl` + `Click` does not work

**Comment by natnat-mc** [comment] 2022-08-28 17:43
It seems using `Get Info > Override Malware Protection` might work to force open the app
I don't see anything sus on [VirusTotal](https://www.virustotal.com/gui/file/989eddd9ac92253bd874c148c40d7204ec13ba62b7fa25a0601fdf042505de84), but [this website](https://www.joesandbox.com/analysis/574091/0/html) classifies it as "SUS" (though their analysis dates from 17-02-2022 so i doubt that's why it suddenly became flagged by Apple)
Honestly it sounds to me like a move from apple to get us to use their product "As Indended" or pay for a middle click app on their store

**Comment by artginzburg** [comment] 2022-09-01 20:45
Duplicate of #29.

Also, we discussed something relevant to a different issue here by accident :)

**Closed by artginzburg** 2022-09-01 20:45 UTC
